export const conference = {
  name: '1st International Conference on Computational Intelligence and Networked Systems (IC2INS-2026)',
  shortName: 'IC2INS-2026',
  theme: 'Intelligent Systems and Smart Networks for a Sustainable Digital Future',
  about: [
    'The 1st International Conference on Computational Intelligence and Networked Systems (IC2INS-2026) is themed around "Intelligent Systems and Smart Networks for a Sustainable Digital Future." The conference will cover a wide range of interdisciplinary research areas, including but not limited to artificial intelligence, deep learning, natural language processing, computer vision, medical imaging, wireless sensor networks, 5G/6G technologies, Internet of Things (IoT), cyber-physical systems, blockchain, smart cities, big data analytics, and cloud-edge-fog computing. The objective is to provide a platform for researchers, academicians, and industry professionals to share innovative solutions, theoretical advances, and practical applications that align with the global shift toward intelligent, connected, and sustainable systems.',
    'The conference is expected to be published by CRC Press (Approval Pending).',
  ],
};

export const speakers = [
  {
    name: 'Dr. Anand Paul',
    role: 'Invited Speaker',
    photo: '/site/images/speaker/Anand Paul.jpeg',
    title: 'Associate Professor',
    affiliation:
      'Department of Biostatistics and Data Science, School of Public Health, Louisiana State University Health Sciences Center, New Orleans, USA',
    summary: [
      'Dr. Anand Paul is an Associate Professor in the Department of Biostatistics and Data Science, School of Public Health, Louisiana State University Health Sciences Center, New Orleans, USA. His academic profile spans artificial intelligence, data science, mathematical modeling of machine learning, and resilient intelligent computing systems.',
      'He previously held academic appointments with Kyungpook National University and Hanyang University in South Korea, contributing to research and teaching in computer science, electronics engineering, and intelligent computing.',
    ],
    signature:
      'Professional focus: resilient and evolving intelligence for data-driven, adaptive, and trustworthy digital systems.',
    education:
      'Ph.D. in Electrical and Computer Engineering, National Cheng Kung University, Taiwan, R.O.C. (2010)',
    institutionalExperience: [
      'Associate Professor, Louisiana State University Health Sciences Center, Department of Biostatistics and Data Science',
      'Professor, Kyungpook National University, School of Computer Science and Engineering',
      'Assistant Professor, Hanyang University, Electronics Engineering',
      'Assistant Professor and Associate Professor, Kyungpook National University, School of Computer Science and Engineering',
    ],
    contributions: [
      'Research interests include artificial intelligence, mathematical modeling of machine learning, and applied machine learning.',
      'Delegate representing South Korea for the M2M focus group and MPEG from 2004 to 2010.',
      'Chair for ACM SAC from 2014 to 2019.',
      'Editorial contributions include Computer Animation and Virtual Worlds, Data Science in Science, IET WSS, ICT Express, Cyber-Physical Systems (Taylor & Francis), and ACM Applied Computing Review.',
    ],
    subjectTags: [
      'Artificial Intelligence',
      'Data Science',
      'Machine Learning',
      'Mathematical Modeling',
      'Resilient Computing',
    ],
    profileNote:
      'For the full profile, publication activity, and editorial record, please visit his PeerJ profile.',
    profileUrl: 'https://peerj.com/anandpaul/',
  },
];

export const callForPapersIntro =
  'Authors are invited to contribute to the conference by submitting original research articles that illustrate novel findings, significant projects, comprehensive surveys, or industrial experiences in the fields of Computational Intelligence and Networked Systems (IC2INS-2026). Submissions should highlight advancements, challenges, and opportunities within these domains.';

export const tracks = [
  {
    title: 'Track 1: Artificial Intelligence (AI)',
    topics: [
      'Neural Networks',
      'Deep Learning',
      'Natural Language Processing',
      'Expert Systems',
      'Reinforcement Learning',
      'Fuzzy Logic and Evolutionary Computation',
      'Sentiment Analysis',
      'AI in Healthcare and Diagnostics',
      'Multi-agent Systems',
    ],
  },
  {
    title: 'Track 2: Advanced Networked Systems and Communication Technologies',
    topics: [
      'Wireless Sensor Networks and 5G/6G Technologies',
      'Internet of Things (IoT) and Industrial IoT',
      'Network Security, Blockchain, and Cryptography',
      'Software-Defined Networking (SDN) and Network Function Virtualization (NFV)',
      'Edge, Fog, and Cloud Networking Architectures',
      'Communication Protocols and Standards',
      'Vehicular Ad-hoc Networks (VANETs)',
      'Satellite and Optical Communication',
      'Network Modeling and Simulation',
    ],
  },
  {
    title: 'Track 3: Machine Vision and Smart Perception',
    topics: [
      'Computer Vision',
      'Image and Video Processing',
      'Medical Imaging and Diagnostics',
      'Remote Sensing and GIS',
      'Brain-Computer Interfaces',
      'Gesture and Emotion Recognition',
      'Object Detection and Scene Understanding',
      'Autonomous Surveillance Systems',
    ],
  },
  {
    title: 'Track 4: Emerging Trends in Computer Technologies',
    topics: [
      'Big Data and Data Analytics',
      'Cyber-Physical Systems',
      'Smart Cities and Digital Infrastructure',
      'Machine-to-Machine Communication',
      'Blockchain and Distributed Ledger Technologies',
      'Internet of Everything (IoE)',
      'Mobile and Cloud Applications',
      'Green and Sustainable Computing',
      'Social and Web Computing',
    ],
  },
];

export const importantDates = [
  { task: 'Paper Submission Start', date: '20 July 2026' },
  { task: 'Paper Submission Deadline', date: '25 Oct 2026' },
  { task: 'Decision Notification', date: '10 Nov 2026' },
  { task: 'Camera Ready Submission', date: '20 Nov 2026' },
  { task: 'Registration', date: '20 Nov 2026' },
  { task: 'Conference Date', date: '3-4 Dec 2026' },
];

export const registrationFees = [
  {
    category: 'Graduate Students (BE/BTech)',
    inr: '10500',
    usd: '200',
  },
  {
    category: 'Faculty and Research Scholars (ME/PhD)',
    inr: '11000',
    usd: '250',
  },
  {
    category: 'Industry',
    inr: '12000',
    usd: '350',
  },
  {
    category: 'Attendee Only',
    inr: '1500',
    usd: '100',
  },
];

export const registrationNotes = [
  'For extra pages (more than 6), per page 1000 INR for Indian and 50 USD for Foreign.',
  'Registration fee once submitted cannot be refunded.',
];

export const submissionGuidelines = [
  'Remove header and footer (if any) in the final camera ready manuscript.',
  'Do not put any page numbers in the camera ready manuscript.',
  'Remove titles like Prof., Dr., Mr., Ms. before author names.',
  'Remove hyperlinks in the final version of the manuscript.',
  'Format the paper using the CRC standard template (Word or LaTeX).',
  'The paper length should not exceed six (6) pages.',
];

export const cameraReadySubmission = {
  intro:
    'Authors are required to follow all the instructions listed under General and Required category for final submission of their manuscript to CRC Press.',
  generalInstructions: [
    'Authors are required to remove header and footer (if there any) in their Final Camera ready manuscript.',
    'Do not put any page numbers in the Camera ready manuscript.',
    'Remove the titles like (Prof., Dr., Mr., Ms., etc..) before the author name(s)',
    'Remove hyperlinks (if there any) in the final version of the manuscripts',
    {
      text: 'Format the paper using CRC standard template',
      links: [
        {
          label: 'Word',
          href: 'https://www.cuchd.in/incacct/assets/uploads/conference-template-a4.pdf',
        },
        {
          label: 'LaTeX',
          href: 'https://www.ieee.org/conferences/publishing/templates',
        },
      ],
    },
    'The paper length should not exceed six (6) pages.',
  ],
};

export const registrationProcess =
  'At least one author must register to include the paper in the conference.';

export const organizingCommittee = [
  {
    role: 'Patron',
    members: [
      'Prof. (Dr.) Sailesh Suryanarayan Iyer, I/c. Principal and Professor, Narnarayan Shastri Institute of Technology - Institute of Forensic Sciences and Cyber Security, Jetalpur, Ahmedabad (Affiliated to National Forensics Sciences University, Gandhinagar)',
    ],
  },
  {
    role: 'Conference Chair',
    members: [
      'Prof. (Dr.) Meenu Gupta, Head Conferences and Research Outreach, Chandigarh University, Punjab, India',
      'Prof. (Dr.) Anand Nayyar, Professor, Scientist, Vice-Chairman (Research) and Director (IoT and Intelligent Systems Lab), SCA, Duy Tan University, Da Nang, Vietnam',
    ],
  },
  {
    role: 'Finance Chair',
    members: [
      'Prof. Kriti Gupta, Department of Computer Science and Engineering, Chandigarh University, Punjab, India',
    ],
  },
  {
    role: 'Publicity Chair',
    members: [
      'Dr. Mohd Naved, Associate Professor (Business Analytics), Jaipuria Institute of Management, Noida, India.',
    ],
  },
  {
    role: 'Technical Program Chair',
    members: ['Dr. Ajantha Devi, AP3 Solutions, India.'],
  },
];

export const technicalProgramCommittee = [
  'Prof. Smain Femmam, Strasbourg University of Haute Alsace, France',
  'Prof. Malleswara Talla, Concordia University, Canada',
  'Dr. Dang Ngoc Hoang Thanh, University of Economics Ho Chi Minh City, Vietnam',
  'Dr. Do Thi Thu Trang, National University of Singapore, Singapore',
  'Prof. Alessio Ishizaka, NEOMA Business School, France',
  'Dr. Phan Thi Thu Hong, FPT University, Vietnam',
  'Prof. Ming-Chu Li, Dalian University of Technology, China',
  'Dr. Pratibha Menon, California University of Pennsylvania, USA',
  'Dr. Tran Trung Tin, FPT University, Vietnam',
  'Dr. Durgesh Samadhiya, National Applied Research Laboratories, Taiwan',
  'Prof. Yeonseung Ryu, Myongji University, South Korea',
  'Assoc. Prof. Hai Van Pham, Hanoi University of Science and Technology, Vietnam',
  'Dr. Tri-Hai Nguyen, Van Lang University, Vietnam',
  'Prof. Haijun Zhao, Guangdong University of Finance and Economics, China',
  'Dr. Vo Quoc Trinh, FPT University, Vietnam',
  'Assoc. Prof. Mohd Nazri Ismail, National Defence University of Malaysia, Malaysia',
  'Prof. Picha Shanmugavadivu, Deemed to be University, India',
  'Assoc. Prof. Quang Thuy Ha, Vietnam National University, Vietnam',
  'Dr. Nguyen Gia Tri, FPT University, Vietnam',
  'Prof. Ta-Cheng Chen, National Formosa University, Taiwan',
  'Assoc. Prof. Sang-Heon Lee, University of South Australia, Australia',
  'Assoc. Prof. Tien-Ying Kuo, National Taipei University of Technology, Taiwan',
  'Dr. Ankur Singh Bist, KIET Group of Institutions, India',
  'Prof. Lei Zhang, East China Normal University, China',
  'Dr. Paulo Batista, University of Evora, Portugal',
  'Assist. Prof. Wen-Kuei Wu, Chaoyang University of Technology, Taiwan',
  'Dr. Nguyen Duy Nghiem, University of Greenwich, Vietnam',
  'Dr. Dao Nhu Ngoc, Sejong University, South Korea',
  'Dr. Sheau-Dong Lang, University of Central Florida, USA',
  'Prof. Kwang Sik Chung, Korea National Open University, South Korea',
  'Dr. Tuan Cuong Nguyen, FPT University, Vietnam',
  'Assoc. Prof. Xiaolong Li, University of Electronic Science and Technology of China, China',
  'Prof. Mohammed Abouhawwash, Michigan State University, USA',
  'Dr. Jiaxin Cai, Xiamen University of Technology, China',
  'Dr. Tran Tri Dang, RMIT University, Vietnam',
  'Assoc. Prof. Noel B. Linsangan, Mapua University, Philippines',
  'Assoc. Prof. Noor Zaman, Taylors University, Malaysia',
  'Dr. Da Quach Luyl, FPT University, Vietnam',
  'Dr. Van-Dung Nguyen, Hung Vuong University of Ho Chi Minh City, Vietnam',
  'Dr. Kyi Thar, Mid Sweden University, Sweden',
  'Dr. Anh Khoa Tran, Ton Duc Thang University, Vietnam',
  'Prof. Tae-Seong Kim, KyungHee University, South Korea',
  'Dr. Sarder Fakhrul Abedin, Mid Sweden University, Sweden',
  'Assoc. Prof. Luu Phuong Vo, International University, Vietnam',
  'Dr. Pratibha Menon, Pennsylvania Western University, USA',
  'Dr. Che-Yen Wen, Central Police University, Taiwan',
  'Prof. Mohammad Iqbal, Institut Teknologi Sepuluh Nopember, Indonesia',
  'Assoc. Prof. Le Hong Trang, Ho Chi Minh City University of Technology, Vietnam',
  'Prof. Manar Amayri, Concordia University, Canada',
  'Prof. Myoungbeom Chung, Sungkyul University, South Korea',
  'Assoc. Prof. Imam Mukhlash, Institut Teknologi Sepuluh Nopember, Indonesia',
  'Dr. Lam Pham, Austrian Institute of Technology, Austria',
  'Prof. Masaomi Kimura, Shibaura Institute of Technology, Japan',
  'Prof. Eric B. Blancaflor, Mapua University, Philippines',
  'Dr. Thinh Ba Vuong, Ho Chi Minh City University of Technology, Vietnam',
  'Dr. Joel C. De Goma, Mapua University, Philippines',
  'Assist. Prof. Peter CY Yau, University of Glasgow Singapore, Singapore',
  'Dr. Luong Vuong Nguyen, FPT University, Vietnam',
  'Dr. Pavan Kumar Mishra, National Institute of Technology Raipur, India',
  'Assist. Prof. Ho Chuk Fong, Tunku Abdul Rahman University of Management and Technology, Malaysia',
  'Prof. Hiroyuki Yamauchi, Fukuoka Institute of Technology, Japan',
  'Dr. Tri-Hai Nguyen, Van Lang University, Vietnam',
  'Dr. Khiem Minh Nguyen, Can Tho University, Can Tho, Vietnam',
  'Assoc. Prof. David Freire-Obregon, University of Las Palmas de Gran Canaria (ULPGC), Spain',
  'Assoc. Prof. Xuan Tan Phan, Shibaura Institute of Technology, Japan',
  'Asst. Prof. Hai-Canh Vu, University of Technology of Compiegne, France',
  'Dr. Tho Dai Dang, Korea University of Information and Communications Technology, South Korea and The University of Da Nang, Vietnam',
  'Prof. I-Tung Yang, National Taiwan University of Science and Technology, Taiwan',
  'Dr. Khiem Minh Nguyen, Can Tho University, Vietnam',
  'Assoc. Prof. Satoshi Masuda, Tokyo City University, Japan',
  'Asst. Prof. Hai-Canh Vu, University of Technology of Compiegne, France',
  'Dr. Tho Dai Dang, Vietnam-Korea University of Information and Communications Technology, Vietnam',
  'Dr. Thu Vo Minh Le, FPT University, Vietnam',
  'Dr. Dinh-Cuong Hoang, Greenwich Vietnam, Vietnam',
  'Dr. Hung Huu Nguyen, Le Quy Don Technical University, Vietnam',
  'Dr. Luis Corujo, University of Lisbon, Portugal',
  'Assco. Prof. Thanh-Nghi Doan, An Giang University, Vietnam',
  'Prof. Xiaojie Wang, Beijing University of Posts and Telecommunications, China',
  'Dr. Hendra Tjahyadi, Universitas Pelita Harapan, Indonesia',
  'Dr. Samuel Lukas, Universitas Pelita Harapan, Indonesia',
  'Dr. Tin Trung Tran, FPT University, Vietnam',
  'Prof. Jinhong Yang, INJE University, Republic of Korea',
  'Prof. Ju Wook Jang, Sogang University, Republic of Korea',
  'Dr. Eric Blancaflor, Mapua University, Philippines',
  'Dr. Mary Grace Gravador Hermogenes, Bulacan State University, Philippines',
  'Assoc. Prof. Sang-Heon Lee, Adelaide University, Australia',
  'Dr. Anh Khoa Tran, Big Data Integration Research Center, National Institute of Information and Communications Technology, Japan',
  'Assoc. Prof. Gadde Swetha, B.V Raju Institute of Technology, India',
  'Asst. Prof. Mary Jane Bacong Arcilla, De La Salle University, Philippines',
];

export const advisoryCommittee = [
  'Karan Mahajan, Centre For Research and Innovation, AGC, Amritsar',
  'Deepika, Computer Science Department, Arizona, USA',
  'Bhagchandani Niraj Dineshkumar, Marwadi University, Rajkot, Gujarat, India',
  'Mohammad Shahnawaz Shaikh, Marwadi University, Rajkot, Gujarat, India',
  'Md Mahbub Murshid, King Fahd University of Petroleum and Minerals, Computer Engineering, Saudi Arabia',
  'Anil Kumar Lamba, MM Engineering College, Maharishi Markandeshwar Deemed to be University, Mullana, Ambala, Haryana, India',
  'Pooja Dahiya, Department of Computer Science and Engineering, Kurukshetra University, Kurukshetra, India',
  'Priyanka Jayeshbhai Mangi, Marwadi University, Rajkot, Gujarat, India',
  'Richa Sharma, Chandigarh University, Punjab, India',
  'Dr. S Berlin Shaheema, Information Technology, Easwari Engineering College, Chennai',
  'Nikhil Gurram, HCL Tech, USA',
  'Neha Sharma, CGC College of Engineering, Landran, Mohali, Punjab, India',
  'Inderjeet Singh, Chandigarh University, Mohali, Punjab, India',
  'A. Hency Juliet, Professor, Saveetha University, SIMATS, Kuthambakkam, Tamil Nadu',
  'Geetha Dayalan, PES University, Bangalore, Karnataka, India',
  'Anuj Mehla, SRM University, Delhi-NCR, Sonipat',
  'D. Raghunath Kumar Babu, Rajeev Gandhi Memorial College of Engineering and Technology, Nandyal-518501, Andhra Pradesh',
  'Sonal Shah, Auro University',
  'Khushboo Das, Computer Science and Engineering, Tezpur University, Assam, India',
  'Paurav Goel, University Institute of Engineering, Chandigarh University, Mohali, Punjab, India',
  'Astha Gupta, Assistant Professor, Chitkara University Institute of Engineering and Technology, Chitkara University, Rajpura, Punjab, India',
  'Divyashree D, Christ University, Bengaluru, Karnataka, India',
  'Neetika Gupta, MM Engineering College, MMDU Mullana, Ambala, India',
  'Shikhar Pandey, GL Bajaj Institute of Technology and Management, Noida, India',
  'Somesubhra Panda, Global Institute of Science and Technology, India',
  'Palvi Sharma, Department of CEA, GLA University, Mathura, UP, India',
  'Praveen Tomar, Ofgem, UK',
  'Manas Ghosh, RCC Institute of Information Technology, Kolkata, India',
  'Abhishek Kumar, IISc Bangalore, India',
  'S. P. Santhoshkumar, Vel Tech Rangarajan Dr. Sagunthala R and D Institute of Science and Technology, Avadi, Chennai, Tamilnadu, India',
  'Rahul Azmeera, University of the Cumberlands, Information Technology, USA',
  'Vivek Pandey, ARMIET, University of Mumbai, India',
  'Aman Kumar, Keral Verma Subharti College Of Science, Swami Vivekanand Subharti University, Meerut',
  'Juily Nachiket Tarade, St. John College of Engineering and Management, Palghar, Maharashtra, India',
  'Gopalakrishnan Venkatasubbu, Payments Platform The Home Depot, Atlanta, GA, USA',
  'Jayakumar Ramalingam, SiriusXM, USA',
  'Aparna Gullapelly, HITAM, Hyderabad, Telangana, India',
  'Ravi Kiran Pagidi, Navy Federal Credit Union, USA',
  'Krishna Kishor Tirupati, Microsoft Corporation, USA',
  'Kush Patel, Oracle America Inc, USA',
  'Kush Patel, Oracle America Inc, USA',
  'Prithvi Raj Veluchamy, Home Depot, USA',
  'Harshavardhan Peddireddy, Platform Architect, Meijer INC, Michigan, USA',
  'Nivetha R, Dayananda Sagar University, India',
  'Saravana Kumar E, The Oxford College of Engineering, Bengaluru, India',
  'Samuel Tensingh, Western Sydney University, Australia',
  "Hari Krishna Pokala, St. Joseph's College of Engineering, Chennai, Tamil Nadu, India",
  'Kishore Arul, CVS Health and Eastern University, USA',
  'Vanitha M, Kongunadu College of Engineering and Technology, Tamilnadu, India',
  'Praveen Kumar Guraja, Oregon Institute of Technology, USA',
  'Nirbhay Kumar Mishra, CGC University, Mohali, Punjab, 140307, India',
  'Jose Prabhu Michael Singarayan, Quantum Integrators, Information Technology, USA',
  'Sheik Jamil Ahmed, Madanapalle Institute of Technology and Science, Andhra Pradesh, India',
  'Anusha Mukka, Meta Platforms Inc, USA',
  'Yusuf Owolabi Olatunde, Osun State University, Osogbo, Nigeria',
  'Gaurav Kumar Singh, Sharda University, Greater Noida, India',
  'Sajad Wani, Assistant Professor, Government College of Engineering and Technology, Safapora, Kashmir, Jammu and Kashmir',
  'Dr. Mitu Sehgal, PIET, Samalkha, India',
  'Anant Wairagade, Independent Researcher, Phoenix, USA',
  'Neeraj Kumar Jha, G H Raisoni University, Amravati, Maharashtra, India',
  'Sudip Barik, Techno International New Town, Department of MCA, Kolkata, India',
  'Sujilatha T, Computer Science and Engineering, NBKRIST, Vidyanagar, Gudur 524413, Nellore Dist, Andhra Pradesh',
  'Botchu Rajani, NBKRIST, Vidyanagar, Gudur, Nellore District, Andhra Pradesh',
  'Nitin Rathour, Delhi Technological University, Delhi, India',
  'Divya Sharma, Amity University, Mohali, Punjab, India',
  'N. Karthik, VLB Janakiammal College of Arts and Science (Autonomous) Coimbatore, India',
  'Djebbar Akila, LRI Laboratory, BP 12, Badji Mokhtar University, Annaba, Algeria',
  'R Ashok, Galgotias University, Greater Noida, UP, India',
  'Aldrin Manon, Uttaranchal Institute of Technology, Uttaranchal University, Premnagar, Dehradun',
  'Bitto Benny, CHRIST College Pune, India',
  'Jogeswar Tripathy, ITER, SIKSHA O ANUSANDHAN Deemed to be University, Bhubaneswar, Odisha',
  'Paritosh Kumar Yadav, National Institute of Technology, Raipur',
  'Aditya Dubey, National Forensic Sciences University, Jaipur',
  'Narinder Kumar, Rayat Bahra University, India',
  'M. V. Vijaya Saradhi, ACE Engineering College, Hyderabad, Telangana, India',
  'Sandeep Wadekar, Parul University, Vadodara',
  'Jatinkumar Soni, Shri Mata Vaishno Devi University, India',
  'Mohammad Zunnun Khan, College of Computing and Information Technology, University of Bisha, KSA',
  'Chaitanay Vinayak Narayan, Amity University, India',
  'Prabu U., Velagapudi Ramakrishna Siddhartha School of Engineering, Siddhartha Academy of Higher Education (Deemed to be University)',
  'Jayanthiladevi, Adichunchangiri University, Karnataka, India',
  'Mohanraj, Sona College of Technology, Salem, India',
  'Anjali Bansal, Delhi Technological University, Department of Computer Science and Engineering, India',
  'Maruf Farhan, Ulster University, United Kingdom',
  'Anita Goyal, Rayat Bahra University, India',
  'Nilesh Kumar Sen, ABES Engineering College, Ghaziabad, NCR, UP, India',
  'Shiva Manoj, Lal Bahadur Shastri Institute, India',
  'Kishorebabu Dasari, Keshav Memorial Institute of Technology, India',
  'Narayana Rao Appini, Department of IT and AI and DS, NBKRIST',
  'Bikram Bikash Das, National Institute of Technology, Silchar, Assam, India',
  'Kumar Gaurav, IIT Roorkee, India',
  'Marouane Marhoun, National School of Applied Sciences, Abdelmalek Essaadi University, Tetouan, Morocco',
  'Dr. Shefali Parihar, Indus University, Ahmedabad',
  'Anam Shamim Ahmad Khan, Mumbai, Maharashtra, India',
  'Diego P. Pinto-Roa, Facultad Politecnica, Universidad Nacional de Asuncion, PY',
  'Iraq Ahmad Reshi, Islamic University of Science and Technology, Awantipora, Kashmir',
  'Chandrayee Kumar, UST GLOBAL, United States',
  'Rama Krishna Reddy Arumalla, Tesla',
  "M R Archana Jenis, St. Joseph's College of Engineering, Department of Computer Science and Engineering, India",
  'Parikshit Sahagal, Independent Researcher, USA',
  'Sugumari Vallinayagam, Department of Biotechnology, Vel Tech Rangarajan Dr. Sagunthala R and D Institute of Science and Technology, Avadi',
  'Sandipan Ghosal, CSE, Techno International New Town, India',
  'Sowmith Reddy Thukkani, University of Cumberlands, USA',
  'Sameena Begam Savukath Ali, Southern New Hampshire University, Information Technology, USA',
  'Madhankumar Natarajan, Belhaven University, Information Technology, USA',
  'Soma Chatterjee, Techno International New Town, Kolkata, India',
  'M Anandaraj, Department of Information Technology, PSNA College of Engineering and Technology, Tamilnadu, India',
  'Satyanarayana Gadiraju, Horizon Blue Cross Blue Shield of New Jersey, SME in Cybersecurity Engineer and Cloud, USA',
  'Sandeep Nanda, Department of Computer Engineering, Koneru Lakshmaiah Educational Foundation Deemed to be University, Guntur, Andhra Pradesh, India',
  'Mir Mehedi Rahman, IT, Emporia State University, USA',
  'Madhuri Latha Gondi, Carnival, USA',
  'Vivek Arora, Walmart Inc, USA',
  'Anamika Kumari, Microsoft, USA',
  'Anamika Kumari, Microsoft, United States',
  'Advitya Gemawat, Microsoft Corporation, US',
  'Neetu Uthaman, Data and Intelligence, Cloud Platforms, Product Management, USA',
  'Arunkumar Amaran, Macys System and Technology, United States',
  'Rajan Singh, Delhi Skill Entrepreneurship University',
  'Rocky Kumar, Poornima University, Jaipur, India',
  'Urmila S Soni, Amity School of Engineering and Technology, Amity University Chhattisgarh, Raipur, India',
  'G Fathima, Adhiyamaan College of Engineering, Hosur, Tamil Nadu, India',
  'Sathish Krishna Anumula, IBM Corporation, USA',
  'Praveen Chaitanya Jakku, HHS Technology Group, USA',
  'Mohit Garg, Cognizant Technology Solutions, USA',
  'Lily Bharati Sharma, Tata Consultancy Services, USA',
  'Milankumar Rana, University of the Cumberlands, University in Williamsburg, Kentucky',
  'Ravi Kiran Pagidi, Navy Federal Credit Union, USA',
];

export const cmtAcknowledgement =
  'The Microsoft CMT service was used for managing the peer-reviewing process for this conference. This service was provided for free by Microsoft and they bore all expenses, including costs for Azure cloud services as well as for software development and support.';

export const contactInfo = {
  name: 'Dr. Meenu Gupta',
  email: 'ic2insconference@gmail.com',
  phone: '+91 94163 45948',
};
